{% set name = "cddlib" %}
{% set version = "0.94m" %}
{% set sha256 = "70dffdb3369b8704dc75428a1b3c42ab9047b81ce039f12f427e2eb2b1b0dee2" %}

package:
  name: {{ name }}
  version: 1!{{ version }}

source:
  url: https://github.com/cddlib/cddlib/releases/download/{{ version }}/cddlib-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - cddlib >=1!{{ version }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - libtool
    - make
  host:
    - gmp
  run:
    - gmp

test:
  commands:
    - test -f ${PREFIX}/include/cddlib/cdd.h
    - test -f ${PREFIX}/lib/libcdd.dylib     # [osx]
    - test -f ${PREFIX}/lib/libcdd.so        # [linux]
    - test -f ${PREFIX}/lib/libcddgmp.dylib  # [osx]
    - test -f ${PREFIX}/lib/libcddgmp.so     # [linux]

about:
  home: https://github.com/cddlib/cddlib
  license: GPLv2
  license_file: COPYING
  summary: An efficient implementation of the Double Description Method
  description: |
    The C-library cddlib is a C implementation of the Double Description Method
    of Motzkin et al. for generating all vertices (i.e. extreme points) and
    extreme rays of a general convex polyhedron in real space given by a system
    of linear inequalities.
  doc_url: ftp://ftp.math.ethz.ch/users/fukudak/cdd/cddlibman/cddlibman.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
