{% set name = "cddlib" %}
{% set version = "0.94" %}
{% set sha256 = "ed81c000565cf98a0b5dd8fa093f62dce8deeb019af491bd7f691237555964ac" %}

package:
  name: {{ name }}
  version: "0.94"

source:
  url: https://github.com/cddlib/cddlib/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # patches from https://github.com/sagemath/sage
    # To make the output consistent across platforms, use a portable rand
    - patches/0001-Add-portable-rand.patch
    # compute reduced H and V representation of polytope for sage.geometry.polyhedron
    - patches/0002-compute-reduced-H-and-V-representation-of-polytope.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - cddlib >=1!{{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
  host:
    - gmp
  run:
    - gmp

test:
  commands:
    - test -f ${PREFIX}/include/cdd.h
    - test -f ${PREFIX}/lib/libcdd.a
    - test -f ${PREFIX}/lib/libcddgmp.a
    - test -f ${PREFIX}/lib/libcdd.dylib     # [osx]
    - test -f ${PREFIX}/lib/libcdd.so        # [linux]
    - test -f ${PREFIX}/lib/libcddgmp.dylib  # [osx]
    - test -f ${PREFIX}/lib/libcddgmp.so     # [linux]

about:
  home: https://github.com/cddlib/cddlib
  license: GPLv2
  license_file: COPYING
  summary: An efficient implementation of the Double Description Method
  description: |
    The C-library cddlib is a C implementation of the Double Description Method
    of Motzkin et al. for generating all vertices (i.e. extreme points) and
    extreme rays of a general convex polyhedron in real space given by a system
    of linear inequalities.
  doc_url: ftp://ftp.math.ethz.ch/users/fukudak/cdd/cddlibman/cddlibman.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
