travis:
  secure:
    BINSTAR_TOKEN: I7RkRzoJRO8DmQc3lSJkt7Gi28Wf/tR9DsF6xfAbESvCDuzBXVW5qVRnsNAMYGDvgGQaOivUGltm1xzzJX5c1Os4CTBiNp9UnkXHcpcpbBpuDA6y3K6bBDn7cm/XcGgmqfzPEHp03NsvxNqPlus7LwRPIkOn8ZZeef1Mv5JqZZAeNW5NuswsNTNXsKzXU8sWqO2X+GNDNG7zbcQmDSreYeSBfIsYDGWRRX12j/xUFIX1yn9Avq/cweTOtZal552JZLyJZuIvdRHpgFTR49G4Y7jAPRHkABuHhjneBGWt68kbgvhKPHZzk3YTQ/QLsr24RQ4GSJHp5zSgokkG/ehT+oGMAbEK/vpLpFnTd4C9PYUeoOUpUs+jjBFLMCo3cHqUfvx1Ah0mwgUlVIn3dfL7aEo05L3UWPgXKzp+DIb+pKt6aEPRpQ4RKmxn1sjBK7xf10S3x0LqO99iaSkR31e1fv7Drk71y2FR00bA+tEVy7CXym9l35YKXmVIV9Ky0k2h0gkzAxc8fnteP7O3MGTxaWSjvHmryORPSGdxEjvFBPKF+6awtYFC5xZsXc80pqtyiP1ubS+4kTDJMTmX6OOc5pX9gZblpN7ct5IhsbX860l4lEJXODP3Q+Tsrr/OyCIIKKVGGmuRYyhj3vcCMjr39Xl+IWtu5ZobJEG+ri9GTg0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
